app/urls.py
from django.urls import path
from .views import cliente_views, orcamento_views, funcionario_views, autenticacao_views

urlpatterns = [
    path('cadastrar_cliente', cliente_views.cadastrar_cliente, name='cadastrar_cliente'),
    path('listar_clientes', cliente_views.listar_clientes, name='listar_clientes'),
    path('lista_cliente/<int:id>', cliente_views.listar_cliente_id, name='listar_cliente_id'),
    path('editar_cliente/<int:id>', cliente_views.editar_cliente, name='editar_cliente'),
    path('editar_orcamento/<int:id>', orcamento_views.editar_orcamento, name='editar_orcamento'),
    path('remover_cliente/<int:id>', cliente_views.remover_cliente, name='remover_cliente'),
    path('remover_orcamento/<int:id>', orcamento_views.remover_orcamento, name='remover_orcamento'),
    path('cadastrar_orcamento/<int:id>', orcamento_views.inserir_orcamento, name='cadastrar_orcamento'),
    path('lista_orcamentos/<int:id>', orcamento_views.listar_orcamento_id, name='listar_orcamento_id'),
    path('cadastrar_funcionario', funcionario_views.inserir_funcionario, name='cadastrar_funcionario'),
    path('listar_funcionarios', funcionario_views.listar_funcionarios, name='listar_funcionarios'),
    path('login', autenticacao_views.login_usuario, name='login'),
    path('logout', autenticacao_views.deslogar_usuario, name='logout'),
    path('enviar_orcamento/<int:id>', orcamento_views.enviar_email_orcamento, name='enviar_orcamento'),
    path('orcamentos/contagem/', orcamento_views.contagem_orcamentos, name='contagem_todos_orcamentos'),
    path('remover_funcionario/<int:id>', funcionario_views.remover_funcionario, name='remover_funcionario')
    ]

orcamentos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include('app.urls'))
]

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_localflavor_br.br_states import STATE_CHOICES
from django.utils import timezone

# Create your models here.

class EnderecoCliente(models.Model):
    rua = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=30, null=False, blank=False)
    estado = models.CharField(max_length=2, choices=STATE_CHOICES, null=False, blank=False)

class Cliente(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    endereco = models.ForeignKey(EnderecoCliente, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, null=False, blank=False)
    telefone = models.CharField(max_length=11,null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    profissao = models.CharField(max_length=25, null=False, blank=False)
    medico_choices = [
        (1, 'Cristiano Dias da Silveira Ramos'),
        (2, 'Érika Lawall Lopoes Ramos')
    ]
    medico = models.IntegerField(choices=medico_choices, null=False, blank=False)

class Orcamento(models.Model):
    forma_pagamento_choices = [
        (1, '1x Cartão de Crédito'),
        (2, '2x Cartão de Crédito'),
        (3, '3x Cartão de Crédito'),
        (4, '4x Cartão de Crédito'),
        (5, '5x Cartão de Crédito'),
        (6, '6x Cartão de Crédito'),
        (7, 'Dinheiro')
    ]

    cirurgias_choices = [
        (1, 'Abdominoplastia'),
        (2, 'Mini-abdominoplastia'),
        (3, 'Blefaroplastia Superior'),
        (4, 'Blefaroplastia Inferior'),
        (5, 'Blefaroplastia Superior e Inferior'),
        (6, 'Braquioplastia'),
        (7, 'Face'),
        (8, 'Lipoaspiração'),
        (9, 'Lipoaspiração de Dorso'),
        (10, 'Lipoaspiração de Submento'),
        (11, 'Mama Redutora'),
        (12, 'Mamoplastia de Aumento'),
        (13, 'Mastopexia'),
        (14, 'Mastopexia com Prótese'),
        (15, 'Ninfoplastia'),
        (16, 'Otoplastia'),
        (17, 'Retoque'),
        (18, 'Rinoplastia'),
        (19, 'Tumores cutâneos')
    ]   

    pac = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=False, blank=False)
    data = models.DateField(null=False, blank=False, auto_now_add=True)
    
    nomeorc = models.CharField(max_length=200, null=False, blank=False)
    descr = models.CharField(max_length=400, null=False, blank=False)

    proc1 = models.IntegerField(choices=cirurgias_choices, null=False, blank=False)
    val1 = models.FloatField(null=True, blank=True)
    pag1 = models.IntegerField(choices=forma_pagamento_choices, null=False, blank=False)

    proc2 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val2 = models.FloatField(null=True, blank=True)
    pag2 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc3 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val3 = models.FloatField(null=True, blank=True)
    pag3 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc4 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val4 = models.FloatField(null=True, blank=True)
    pag4 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc5 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val5 = models.FloatField(null=True, blank=True)
    pag5 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc6 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val6 = models.FloatField(null=True, blank=True)
    pag6 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    data_ultima_alteracao = models.DateTimeField(default=timezone.now, editable=False)

    def datatt(self, *args, **kwargs):
        self.data_ultima_alteracao = timezone.now()
        super(Orcamento, self).save(*args, **kwargs)
    
    def total(self):
        return (self.val1 or 0) + (self.val2 or 0) + (self.val3 or 0) + (self.val4 or 0) + (self.val5 or 0) + (self.val6 or 0)

class Funcionario(AbstractUser):
    CARGO_CHOICES = [
        (1, 'Médico'),
        (2, 'Suporte'),
        (3, 'Atendimento'),
    ]
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    cargo = models.IntegerField(choices=CARGO_CHOICES, null=False, blank=False)

app/forms/cliente_forms.py
from django import forms
from django.forms import DateInput

from ..models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'email','telefone', 'data_nascimento', 'cpf', 'profissao', 'medico']
        widgets = {
            'data_nascimento': DateInput(
                attrs={'type': "date"}
            )
        }
        
class FiltroMedicoForm(forms.Form):
    medicos_choices = [(choice[0], choice[1]) for choice in Cliente.medico_choices]
    Médico = forms.ChoiceField(choices=[('', 'Todos')] + medicos_choices, required=False)
    pesquisa = forms.CharField(max_length=100, required=False, label='Paciente')

app/views/cliente_views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect

from ..forms.cliente_forms import ClienteForm, FiltroMedicoForm
from ..forms.endereco_forms import EnderecoClienteForm
from ..entidades import cliente, endereco
from ..services import cliente_service, endereco_service, orcamento_services

@login_required()
def listar_clientes(request):
    form = FiltroMedicoForm(request.GET)
    clientes = cliente_service.listar_clientes()

    if form.is_valid():
        medico = form.cleaned_data['Médico']
        pesquisa = form.cleaned_data['pesquisa']
        if medico:
            clientes = clientes.filter(medico=medico)
        if pesquisa:
            clientes = clientes.filter(nome__icontains=pesquisa)

    context = {
        'clientes': clientes,
        'form': form,
    }
    return render(request, 'clientes/lista_clientes.html', context)

@user_passes_test(lambda u: u.cargo==1)
def listar_cliente_id(request, id):
    cliente = cliente_service.listar_cliente_id(id)
    orcamento = orcamento_services.listar_orcamento(id)
    return render(request, 'clientes/lista_cliente.html', {'cliente': cliente, 'orcamento':orcamento})

@user_passes_test(lambda u: u.cargo==1)
def remover_cliente(request, id):
    cliente = cliente_service.listar_cliente_id(id)
    endereco = endereco_service.listar_endereco_id(cliente.endereco.id)
    if request.method == "POST":
        cliente_service.remover_cliente(cliente)
        endereco_service.remover_endereco(endereco)
        return redirect('listar_clientes')
    return render(request, 'clientes/confirma_exclusao.html', {'cliente': cliente})

@login_required()
def cadastrar_cliente(request):
    if request.method == "POST":
        form_cliente = ClienteForm(request.POST)
        form_endereco = EnderecoClienteForm(request.POST)
        if form_cliente.is_valid():
            nome = form_cliente.cleaned_data["nome"]
            email = form_cliente.cleaned_data["email"]
            telefone = form_cliente.cleaned_data["telefone"]
            cpf = form_cliente.cleaned_data["cpf"]
            data_nascimento = form_cliente.cleaned_data["data_nascimento"]
            profissao = form_cliente.cleaned_data["profissao"]
            medico = form_cliente.cleaned_data["medico"]
            if form_endereco.is_valid():
                rua = form_endereco.cleaned_data["rua"]
                cidade = form_endereco.cleaned_data["cidade"]
                estado = form_endereco.cleaned_data["estado"]
                endereco_novo = endereco.Endereco(rua=rua, cidade=cidade, estado=estado)
                endereco_bd = endereco_service.cadastrar_endereco(endereco_novo)
                cliente_novo = cliente.Cliente(nome=nome, email=email, telefone=telefone, data_nascimento=data_nascimento,
                                           profissao=profissao, cpf=cpf, endereco=endereco_bd, medico=medico)
                cliente_service.cadastrar_cliente(cliente_novo)
                return redirect('listar_clientes')
    else:
        form_cliente = ClienteForm()
        form_endereco = EnderecoClienteForm()
    return render(request, 'clientes/form_cliente.html', {'form_cliente': form_cliente, 'form_endereco': form_endereco})

@login_required()
def editar_cliente(request, id):
    cliente_editar = cliente_service.listar_cliente_id(id)
    cliente_editar.data_nascimento = cliente_editar.data_nascimento.strftime('%Y-%m-%d')
    form_cliente = ClienteForm(request.POST or None, instance=cliente_editar)
    endereco_editar = endereco_service.listar_endereco_id(cliente_editar.endereco.id)
    form_endereco = EnderecoClienteForm(request.POST or None, instance=endereco_editar)
    if form_cliente.is_valid():
        nome = form_cliente.cleaned_data["nome"]
        email = form_cliente.cleaned_data["email"]
        telefone = form_cliente.cleaned_data["telefone"]
        cpf = form_cliente.cleaned_data["cpf"]
        data_nascimento = form_cliente.cleaned_data["data_nascimento"]
        profissao = form_cliente.cleaned_data["profissao"]
        medico = form_cliente.cleaned_data["medico"]
        if form_endereco.is_valid():
            rua = form_endereco.cleaned_data["rua"]
            cidade = form_endereco.cleaned_data["cidade"]
            estado = form_endereco.cleaned_data["estado"]
            endereco_novo = endereco.Endereco(rua=rua, cidade=cidade, estado=estado)
            endereco_editado = endereco_service.editar_endereco(endereco_editar, endereco_novo)
            cliente_novo = cliente.Cliente(nome=nome, email=email,telefone=telefone, data_nascimento=data_nascimento,
                                           profissao=profissao, cpf=cpf, endereco=endereco_editado, medico=medico)
            cliente_service.editar_cliente(cliente_editar, cliente_novo)
            return redirect('listar_clientes')
    return render(request, 'clientes/form_cliente.html', {'form_cliente': form_cliente ,'form_endereco': form_endereco})

app/templates/clientes/confirma_exclusao.html
{% extends 'base.html' %}

{% block title %}
Remoção de clientes
{% endblock title %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Tem certeza que deseja remover o cliente abaixo?</h3>
    </div>
    <div class="box-body">
        <h5>Nome: {{cliente.nome}}</h5>
        <h5>Profissão: {{cliente.profissao}}</h5>
        <h5>Data de Nascimento: {{cliente.data_nascimento}}</h5>
        <h5>Email: {{cliente.email}}</h5>
        <h5>CPF: {{cliente.cpf}}</h5>

        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
        </form>
    </div>
</div>


{% endblock content %}

app/templates/clientes/form_cliente.html
{% extends 'base.html' %}

{% load meus_filtros %}

{% block title %}
Cadastro de Pacientes
{% endblock title %}

{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Cadastro de Pacientes</h3>
        </div>
        <div class="box-body">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{form_cliente.medico.errors}}
                    <label>Médico Responsável: </label>
                    {{form_cliente.medico|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.nome.errors}}
                    <label>Nome: </label>
                    {{form_cliente.nome|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.data_nascimento.errors}}
                    <label>Data de nascimento: </label>
                    {{form_cliente.data_nascimento|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.telefone.errors}}
                    <label>Telefone: </label>
                    {{form_cliente.telefone|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.email.errors}}
                    <label>Email: </label>
                    {{form_cliente.email|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    <label>CPF: </label>
                    {{form_cliente.cpf|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.profissao.errors}}
                    <label>Profissão: </label>
                    {{form_cliente.profissao|addclass:'form-control'}}
                </div>
                <hr>
                <h4>Endereço</h4>
                <div class="form-group">
                    {{form_endereco.rua.errors}}
                    <label>Rua: </label>
                    {{form_endereco.rua|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_endereco.cidade.errors}}
                    <label>Cidade: </label>
                    {{form_endereco.cidade|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_endereco.estado.errors}}
                    <label>Estado: </label>
                    {{form_endereco.estado|addclass:'form-control'}}
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary" name="Cadastrar">
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

app/templates/clientes/lista_cliente.html
{% extends 'base.html' %}

{% block title %}
Listagem de Orçamentos
{% endblock title %}

{% block content %}
<head>
  <style>
    .timeline-body {
      word-wrap: break-word;

      overflow-y: auto;
    }
    button {
      margin-right: 10px;
    }
    .fa-calendar {
      color: black;
    }
  </style>
</head>
<section class="content">
  <div class="row">
    <div class="col-md-4">
      <!-- Profile Image -->
      <div class="box box-primary">
        <div class="box-body box-profile">
          <h3 class="profile-username text-center">{{cliente.nome}}</h3>

          <p class="text-muted text-center">{{cliente.profissao}}</p>
          <p class="text-muted text-center">{{cliente.get_medico_display}}
          <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
              <b>Nascimento</b> <a
                class="pull-right">{{cliente.data_nascimento}}</a>
            </li>
            <li class="list-group-item">
              <b>CPF</b> <a class="pull-right">{{cliente.cpf}}</a>
            </li>
            <li class="list-group-item">
              <b>Telefone</b> <a class="pull-right">{{cliente.telefone}}</a>
            </li>
            <li class="list-group-item">
              <b>E-mail</b> <a class="pull-right">{{cliente.email}}</a>
            </li>
          </ul>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      <!-- About Me Box -->
      <div class="box box-primary">
        <div class="box-header with-border">
        </div>
        <div class="row">
          <div class="col-md-12">
            <a href="{% url 'cadastrar_orcamento' cliente.id %}"
              class="btn btn-primary btn-block">Cadastrar Orçamento</a>
          </div>
        </div>

      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  <!-- /.col -->
  <div class="col-xs-8">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#timeline" data-toggle="tab">Histórico</a>
        </li>
      </ul>
      <div class="tab-content">
        <div class="active tab-pane" id="timeline">
          <ul class="timeline timeline-inverse">
            <li class="time-label">
              <span class="bg-blue">
                {% now "SHORT_DATE_FORMAT" %}
              </span>
            </li>

            {% for orcamentos in orcamento %}

            <li>
              <i class="fa fa-stethoscope bg-blue"></i>
              <div class="timeline-item">
                <span class="time"> <i class="fa fa-calendar"></i>
                  {{orcamentos.data}}
                </span>
                <h3 class="timeline-header">
                  Novo Orçamento: {{orcamentos.nomeorc}}
                </h3>
                <div class="timeline-body">
                  {{orcamentos.descr}}
                </div>
                <div class="timeline-footer">
                  <a class="btn btn-primary btn-xs"
                    href="{% url 'listar_orcamento_id' orcamentos.id %}">
                    Visualizar Orçamento
                  </a>

                  <a class="btn btn-primary btn-xs"
                    href="{% url 'editar_orcamento' orcamentos.id %}">
                    Editar
                  </a>

                  <a class="btn btn-danger btn-xs"
                  href="{% url 'remover_orcamento' orcamentos.id %}">
                  Excluir
                  </a>
                </div>
              </div>
            </li>
            {% endfor %}

            <!-- END timeline item -->

            <li>
              <i class="fa fa-clock-o bg-gray"></i>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- /.col -->
  </div>
  <!-- /.row -->

</section>
{% endblock content %}

app/templates/clientes/lista_clientes.html
{% extends 'base.html' %}

{% block title %}
Listagem de Pacientes
{% endblock title %}

{% block content %}
<head>
    <style>
        .form-container {
            display: flexbox;
            flex-direction: row;
            margin-bottom: 10px;
        }

        .form-group {
            display: inline;
            flex-direction: row;
            margin-bottom: 10px;
            margin-right: 1%;
        }

        .button-container {
            display: inline;
            flex-direction: column;
        }
    </style>
</head>
<div class="form-container">
    <form method="get" action="{% url 'listar_clientes' %}">
        <div class="form-group">
            {{ form.pesquisa.label_tag }}
            {{ form.pesquisa }}
        </div>
        <div class="form-group">
            {{ form.Médico.label_tag }}
            {{ form.Médico }}
        </div>
        <button type="submit" class="btn btn-primary">Filtrar</button>
    </form>
</div>
<div class="form-container">
    <a href="{% url 'cadastrar_cliente' %}">
        <button class="btn btn-primary">Cadastrar</button>
    </a>
</div>
<div class="box box-primary">
    <div class="box-body">
        <div class="box-header with-border">
            <h3 class="box-title">Lista de Pacientes</h3>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Médico</th>
                    <th>Data de Nascimento</th>
                    <th>E-mail</th>
                    <th>Telefone</th>
                    <th>Profissão</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr>
                    <td>     
                        <a href="{% url 'listar_cliente_id' cliente.id %}">{{cliente.nome}}</a>
                    </td>
                    <td>{{cliente.get_medico_display}}</td>
                    <td>{{cliente.data_nascimento}}</td>
                    <td>{{cliente.email}}</td>
                    <td>{{cliente.telefone}}</td>
                    <td>{{cliente.profissao}}</td>
                    <td>
                        <a href="{% url 'editar_cliente' cliente.id %}">Editar</a>
                        <a href="{% url 'remover_cliente' cliente.id %}">Remover</a>
                    </td>
                {% endfor %}
                </tr>
            </tbody>
        </table>
        <hr>
    </div>
</div>
{% endblock content %}